baseurl: "/type-theme"
url: "https://are-dynamic-2024-g4.github.io/algo-genetique/"
theme_settings:
  title: Algorithme Génétique 
  description: Modele python d'un algorithme génétique représentant la selection naturelle de Darwin

  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock


-jekyll-remote-theme
