remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
title: "Algorithme Génétique "
description: "Modele python d'un algorithme génétique représentant la selection naturelle de Darwin"

